/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeDeckIdRouteImport } from './routes/practice.$deckId'
import { Route as McqTestIdRouteImport } from './routes/mcq.$testId'
import { Route as McqResultTestIdRouteImport } from './routes/mcq-result.$testId'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeDeckIdRoute = PracticeDeckIdRouteImport.update({
  id: '/practice/$deckId',
  path: '/practice/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const McqTestIdRoute = McqTestIdRouteImport.update({
  id: '/mcq/$testId',
  path: '/mcq/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const McqResultTestIdRoute = McqResultTestIdRouteImport.update({
  id: '/mcq-result/$testId',
  path: '/mcq-result/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/summary': typeof SummaryRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/mcq-result/$testId': typeof McqResultTestIdRoute
  '/mcq/$testId': typeof McqTestIdRoute
  '/practice/$deckId': typeof PracticeDeckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/summary': typeof SummaryRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/mcq-result/$testId': typeof McqResultTestIdRoute
  '/mcq/$testId': typeof McqTestIdRoute
  '/practice/$deckId': typeof PracticeDeckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/summary': typeof SummaryRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/mcq-result/$testId': typeof McqResultTestIdRoute
  '/mcq/$testId': typeof McqTestIdRoute
  '/practice/$deckId': typeof PracticeDeckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/summary'
    | '/admin'
    | '/mcq-result/$testId'
    | '/mcq/$testId'
    | '/practice/$deckId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/summary'
    | '/admin'
    | '/mcq-result/$testId'
    | '/mcq/$testId'
    | '/practice/$deckId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/summary'
    | '/_authenticated/admin'
    | '/mcq-result/$testId'
    | '/mcq/$testId'
    | '/practice/$deckId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SummaryRoute: typeof SummaryRoute
  McqResultTestIdRoute: typeof McqResultTestIdRoute
  McqTestIdRoute: typeof McqTestIdRoute
  PracticeDeckIdRoute: typeof PracticeDeckIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$deckId': {
      id: '/practice/$deckId'
      path: '/practice/$deckId'
      fullPath: '/practice/$deckId'
      preLoaderRoute: typeof PracticeDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcq/$testId': {
      id: '/mcq/$testId'
      path: '/mcq/$testId'
      fullPath: '/mcq/$testId'
      preLoaderRoute: typeof McqTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcq-result/$testId': {
      id: '/mcq-result/$testId'
      path: '/mcq-result/$testId'
      fullPath: '/mcq-result/$testId'
      preLoaderRoute: typeof McqResultTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SummaryRoute: SummaryRoute,
  McqResultTestIdRoute: McqResultTestIdRoute,
  McqTestIdRoute: McqTestIdRoute,
  PracticeDeckIdRoute: PracticeDeckIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
