/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as SaathiRouteImport } from './routes/saathi'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as McqTestsRouteImport } from './routes/mcq-tests'
import { Route as McqPracticeRouteImport } from './routes/mcq-practice'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeDeckIdRouteImport } from './routes/practice.$deckId'
import { Route as PracticeMcqTestIdRouteImport } from './routes/practice-mcq.$testId'
import { Route as McqTestIdRouteImport } from './routes/mcq.$testId'
import { Route as McqResultTestIdRouteImport } from './routes/mcq-result.$testId'
import { Route as AuthenticatedBotManagerRouteImport } from './routes/_authenticated/bot-manager'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SaathiRoute = SaathiRouteImport.update({
  id: '/saathi',
  path: '/saathi',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const McqTestsRoute = McqTestsRouteImport.update({
  id: '/mcq-tests',
  path: '/mcq-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const McqPracticeRoute = McqPracticeRouteImport.update({
  id: '/mcq-practice',
  path: '/mcq-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeDeckIdRoute = PracticeDeckIdRouteImport.update({
  id: '/practice/$deckId',
  path: '/practice/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeMcqTestIdRoute = PracticeMcqTestIdRouteImport.update({
  id: '/practice-mcq/$testId',
  path: '/practice-mcq/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const McqTestIdRoute = McqTestIdRouteImport.update({
  id: '/mcq/$testId',
  path: '/mcq/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const McqResultTestIdRoute = McqResultTestIdRouteImport.update({
  id: '/mcq-result/$testId',
  path: '/mcq-result/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBotManagerRoute = AuthenticatedBotManagerRouteImport.update({
  id: '/bot-manager',
  path: '/bot-manager',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/flashcards': typeof FlashcardsRoute
  '/mcq-practice': typeof McqPracticeRoute
  '/mcq-tests': typeof McqTestsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/saathi': typeof SaathiRoute
  '/summary': typeof SummaryRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bot-manager': typeof AuthenticatedBotManagerRoute
  '/mcq-result/$testId': typeof McqResultTestIdRoute
  '/mcq/$testId': typeof McqTestIdRoute
  '/practice-mcq/$testId': typeof PracticeMcqTestIdRoute
  '/practice/$deckId': typeof PracticeDeckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/flashcards': typeof FlashcardsRoute
  '/mcq-practice': typeof McqPracticeRoute
  '/mcq-tests': typeof McqTestsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/saathi': typeof SaathiRoute
  '/summary': typeof SummaryRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bot-manager': typeof AuthenticatedBotManagerRoute
  '/mcq-result/$testId': typeof McqResultTestIdRoute
  '/mcq/$testId': typeof McqTestIdRoute
  '/practice-mcq/$testId': typeof PracticeMcqTestIdRoute
  '/practice/$deckId': typeof PracticeDeckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/flashcards': typeof FlashcardsRoute
  '/mcq-practice': typeof McqPracticeRoute
  '/mcq-tests': typeof McqTestsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/saathi': typeof SaathiRoute
  '/summary': typeof SummaryRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bot-manager': typeof AuthenticatedBotManagerRoute
  '/mcq-result/$testId': typeof McqResultTestIdRoute
  '/mcq/$testId': typeof McqTestIdRoute
  '/practice-mcq/$testId': typeof PracticeMcqTestIdRoute
  '/practice/$deckId': typeof PracticeDeckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/flashcards'
    | '/mcq-practice'
    | '/mcq-tests'
    | '/privacy-policy'
    | '/saathi'
    | '/summary'
    | '/terms'
    | '/admin'
    | '/bot-manager'
    | '/mcq-result/$testId'
    | '/mcq/$testId'
    | '/practice-mcq/$testId'
    | '/practice/$deckId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/flashcards'
    | '/mcq-practice'
    | '/mcq-tests'
    | '/privacy-policy'
    | '/saathi'
    | '/summary'
    | '/terms'
    | '/admin'
    | '/bot-manager'
    | '/mcq-result/$testId'
    | '/mcq/$testId'
    | '/practice-mcq/$testId'
    | '/practice/$deckId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/flashcards'
    | '/mcq-practice'
    | '/mcq-tests'
    | '/privacy-policy'
    | '/saathi'
    | '/summary'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/bot-manager'
    | '/mcq-result/$testId'
    | '/mcq/$testId'
    | '/practice-mcq/$testId'
    | '/practice/$deckId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FlashcardsRoute: typeof FlashcardsRoute
  McqPracticeRoute: typeof McqPracticeRoute
  McqTestsRoute: typeof McqTestsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SaathiRoute: typeof SaathiRoute
  SummaryRoute: typeof SummaryRoute
  TermsRoute: typeof TermsRoute
  McqResultTestIdRoute: typeof McqResultTestIdRoute
  McqTestIdRoute: typeof McqTestIdRoute
  PracticeMcqTestIdRoute: typeof PracticeMcqTestIdRoute
  PracticeDeckIdRoute: typeof PracticeDeckIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saathi': {
      id: '/saathi'
      path: '/saathi'
      fullPath: '/saathi'
      preLoaderRoute: typeof SaathiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcq-tests': {
      id: '/mcq-tests'
      path: '/mcq-tests'
      fullPath: '/mcq-tests'
      preLoaderRoute: typeof McqTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcq-practice': {
      id: '/mcq-practice'
      path: '/mcq-practice'
      fullPath: '/mcq-practice'
      preLoaderRoute: typeof McqPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$deckId': {
      id: '/practice/$deckId'
      path: '/practice/$deckId'
      fullPath: '/practice/$deckId'
      preLoaderRoute: typeof PracticeDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-mcq/$testId': {
      id: '/practice-mcq/$testId'
      path: '/practice-mcq/$testId'
      fullPath: '/practice-mcq/$testId'
      preLoaderRoute: typeof PracticeMcqTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcq/$testId': {
      id: '/mcq/$testId'
      path: '/mcq/$testId'
      fullPath: '/mcq/$testId'
      preLoaderRoute: typeof McqTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcq-result/$testId': {
      id: '/mcq-result/$testId'
      path: '/mcq-result/$testId'
      fullPath: '/mcq-result/$testId'
      preLoaderRoute: typeof McqResultTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bot-manager': {
      id: '/_authenticated/bot-manager'
      path: '/bot-manager'
      fullPath: '/bot-manager'
      preLoaderRoute: typeof AuthenticatedBotManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBotManagerRoute: typeof AuthenticatedBotManagerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBotManagerRoute: AuthenticatedBotManagerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FlashcardsRoute: FlashcardsRoute,
  McqPracticeRoute: McqPracticeRoute,
  McqTestsRoute: McqTestsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SaathiRoute: SaathiRoute,
  SummaryRoute: SummaryRoute,
  TermsRoute: TermsRoute,
  McqResultTestIdRoute: McqResultTestIdRoute,
  McqTestIdRoute: McqTestIdRoute,
  PracticeMcqTestIdRoute: PracticeMcqTestIdRoute,
  PracticeDeckIdRoute: PracticeDeckIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
